
// Custom error codes
#define REQUIRES_IGOR_504				1 + FIRST_XOP_ERR
#define NULL_STRING_HANDLE				2 + FIRST_XOP_ERR
#define PROBLEM_UNZIPPING				3 + FIRST_XOP_ERR
#define SYMBOLIC_PATH_ISNT_FOLDER		4 + FIRST_XOP_ERR
#define CANNOT_OPEN_ZIPFILE				5 + FIRST_XOP_ERR
#define CANNOT_CHANGE_DIR				6 + FIRST_XOP_ERR
#define PROBLEM_EXTRACTING				7 + FIRST_XOP_ERR
#define PROBLEM_ZIPPING					8 + FIRST_XOP_ERR
#define CANT_OPEN_TARFILE				9 + FIRST_XOP_ERR
#define NOT_A_FILE_OR_FOLDER			10 + FIRST_XOP_ERR
#define PROBLEM_APPENDING_TO_TAR		11 + FIRST_XOP_ERR
#define CANT_FIND_IN_ZIP				12 + FIRST_XOP_ERR
#define NO_ZIP_BY_THAT_HANDLE			13 + FIRST_XOP_ERR
#define PROBLEM_LISTING_FILES			14 + FIRST_XOP_ERR